name: whispr

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: whispr_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - public
    restart: unless-stopped

volumes:
  postgres:
    driver: local

networks:
  public:
    driver: bridge
