name: whispr

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: whispr_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - public
    restart: unless-stopped

volumes:
  db_data:
    driver: local

networks:
  public:
    driver: bridge
