spring:
  application:
    name: service-discovery

server:
  port: 8761

eureka:
  server:
    enable-self-preservation: false     # Todo: Dev only
  client:
    register-with-eureka: false
    fetch-registry: false
